version: "3.3"

services:
  print:
    image: ghcr.io/khonkaen-hospital/print-label/print-label:1.0.1
    ports:
      - 7007:3000
    volumes:
      - ./.env:/app/.env
    networks:
      - brokernet
networks:
  brokernet:
    driver: bridge
